name: Build And Release

on:
  workflow_dispatch:

jobs:
  Build-GUI:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install pyinstaller && pip install -r GUI-VER/requirements.txt

      - name: Build For ${{ runner.os }}
        run: pyinstaller --onefile GUI-VER/CSDownloader-GUI_BETA.py -n CSDownloader-GUI_${{ runner.os }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: GUI-${{ runner.os }}-artifact
          path: dist/CSDownloader-GUI_${{ runner.os }}*

  Build-TUI:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install pyinstaller && pip install -r requirements.txt

      - name: Build For ${{ runner.os }}
        run: pyinstaller --onefile CSDownloader.py -n CSDownloader-TUI_${{ runner.os }}
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TUI-${{ runner.os }}-artifact
          path: dist/CSDownloader-TUI_${{ runner.os }}*
  
  Extras:
    runs-on: ${{ matrix.os }}
    
    strategy: 
      matrix:
        os: [ ubuntu-latest ]

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Archive PY (GUI) & PY (TUI)
        run: |
          echo -e "Install 'pyinstaller': pip install pyinstaller\nInstall Dependencies: pip install -r requirements.txt\nBuild File: ~/.local/bin/pyinstaller --onefile ./CSDownloader-<  GUI / TUI  >.py" > buildInstructions.txt
          7z a CSDownloader-GUI_PY.zip buildInstructions.txt
          cd GUI-VER
          mv CSDownloader-GUI*.py CSDownloader-GUI.py
          7z a ../CSDownloader-GUI_PY.zip CSDownloader-GUI.py requirements.txt
          cd ..
          mv CSDownloader.py CSDownloader-TUI.py
          7z a CSDownloader-TUI_PY.zip CSDownloader-TUI.py requirements.txt buildInstructions.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PY-artifacts
          path: |
            CSDownloader-GUI_PY.zip
            CSDownloader-TUI_PY.zip
          
  Release:
    needs:
     - Build-GUI
     - Build-TUI
     - Extras
     
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        
      - name: Create Draft Release
        id: createRelease
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          name: Release v
          tag_name: release-v
          fail_on_unmatched_files: true
          files: |
            ./GUI-Linux-artifact/CSDownloader-GUI_Linux
            ./GUI-Windows-artifact/CSDownloader-GUI_Windows.exe
            ./PY-artifacts/CSDownloader-GUI_PY.zip
            ./TUI-Linux-artifact/CSDownloader-TUI_Linux
            ./TUI-Windows-artifact/CSDownloader-TUI_Windows.exe
            ./PY-artifacts/CSDownloader-TUI_PY.zip
