name: Build And Release GUI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your desired Python version

      - name: Install Dependencies
        run: pip install pyinstaller

      - name: Build for ${{ runner.os }}
        run: pyinstaller --onefile GUI-VER/CSDownloader-GUI_BETA.py
        
      - name: Archive Artifacts
        run: 7z a -r GUI-Mode_${{ runner.os }}.zip dist
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-artifact
          path: GUI-Mode_${{ runner.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Debug
        run: ls -a && ls -a ./Linux-artifact && ls -a ./Windows-artifact
        
      - name: Create Draft Release
        id: createRelease
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: /home/runner/work/CurseForgeDownloader2023/CurseForgeDownloader2023
          draft: true
          name: Release v
          tag_name: release-v
          fail_on_unmatched_files: false
          files: |
            ./Linux-artifact/GUI-Mode_Linux.zip
            ./Windows-artifact/GUI-Mode_Windows.zip
