name: Build and Release GUI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your desired Python version

      - name: Install Dependencies
        run: pip install pyinstaller

      - name: Build for ${{ runner.os }}
        run: pyinstaller --onefile GUI-VER/CSDownloader-GUI_BETA.py
        
      - name: Archive Artifacts
        run: 7z a -r GUI-Mode_${{ runner.os }}.zip dist
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: GUI-Mode_${{ runner.os }}.zip
          path: GUI-Mode_${{ runner.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        
      - name: Debug
        run: ls -a && echo -e "\n\n" && ls -a ../../../
        
      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          tag_name: release-x.x
          fail_on_unmatched_files: true
          files: |
            ./GUI-Mode_Linux.zip
            ./GUI-Mode_Windows.zip

      - name: Release URL
        run: echo "Release URL - ${{ steps.create_release.outputs.upload_url }}"
